services:
  notification-service:
    build: ./notification-service
    ports:
      - "8081:8080"
    container_name: notification-service
  order-service:
    build: ./order-service
    ports:
      - "8082:8080"
    container_name: order-service
  payment-service:
    build: ./payment-service
    ports:
      - "8083:8080"
    container_name: payment-service
  product-catalog-service:
    build: ./product-catalog-service
    ports:
      - "8084:8080"
    container_name: product-catalog-service
  shopping-cart-service:
    build: ./shopping-cart-service
    ports:
      - "8085:8080"
    container_name: shopping-cart-service
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
  user-service:
    build: ./user-service
    ports:
      - "8086:8080"
    container_name: user-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
    depends_on:
      - postgres 